In [1]:
import numpy as np 
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pylab as plt

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-dmjpf8ii because the default path (/home/juliosouza/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [2]:
data = pd.read_csv("test_scores.csv")

In [5]:
data.head()

school school_setting school_type classroom teaching_method  n_student  \
0  ANKYI          Urban  Non-public       6OL        Standard       20.0   
1  ANKYI          Urban  Non-public       6OL        Standard       20.0   
2  ANKYI          Urban  Non-public       6OL        Standard       20.0   
3  ANKYI          Urban  Non-public       6OL        Standard       20.0   
4  ANKYI          Urban  Non-public       6OL        Standard       20.0   

  student_id  gender             lunch  pretest  posttest  
0      2FHT3  Female  Does not qualify     62.0      72.0  
1      3JIVH  Female  Does not qualify     66.0      79.0  
2      3XOWE    Male  Does not qualify     64.0      76.0  
3      556O0  Female  Does not qualify     61.0      77.0  
4      74LOE    Male  Does not qualify     64.0      76.0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   school           2133 non-null   object 
 1   school_setting   2133 non-null   object 
 2   school_type      2133 non-null   object 
 3   classroom        2133 non-null   object 
 4   teaching_method  2133 non-null   object 
 5   n_student        2133 non-null   float64
 6   student_id       2133 non-null   object 
 7   gender           2133 non-null   object 
 8   lunch            2133 non-null   object 
 9   pretest          2133 non-null   float64
 10  posttest         2133 non-null   float64
dtypes: float64(3), object(8)
memory usage: 183.4+ KB


There are a lot of the data that is strings that needs to be converted into number. 

Maybe student_id might be not be usefull afterwards.

In [8]:
#Remove the variable student_id which is not usefull
data = data.drop(columns=['student_id'])

In [9]:
#The data is transformed into categorical.
for col in ['school' ,'school_setting', 'school_type', 'classroom', 'teaching_method', 'gender', 'lunch']:
    data[col] = data[col].astype('category')


In [15]:
#enconding the data
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for col in ['school' , 'school_setting', 'school_type', 'classroom', 'teaching_method', 'gender', 'lunch']:
    le.fit(data[col])
    data[col] = le.transform(data[col])
data.head()

In [22]:
def split_train_test(data,test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data)*test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]
train,test = split_train_test(data, 0.2)
x_test = test.drop('posttest',axis = 1)
x_train = train.drop('posttest',axis = 1)
y_test = test['posttest'].values
y_train = train['posttest'].values

Before analyse the feature, lets use all data to predict the students score.

Let's use linear Regretion

In [ ]:
#Check the correlation betweem the features
import seaborn as sns
# Correlation matrix for dataset
plt.figure(figsize=(15,10))
sns.heatmap(data.corr(), annot=True, cmap="inferno")

In [26]:
#Function to select the training and test data
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)
predictions = reg.predict(x_test)

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
predictions = np.round(predictions)
predictions

array([ 67.,  79.,  58.,  62.,  89.,  80.,  44.,  63.,  46.,  56., 101.,
        59.,  79.,  76.,  81.,  87.,  75.,  37.,  52.,  49.,  77.,  81.,
        63.,  52.,  72.,  55.,  49.,  43.,  81.,  55.,  71.,  90.,  81.,
        77.,  84.,  42.,  62.,  81.,  64.,  58.,  72.,  74.,  63.,  55.,
        65.,  76.,  65.,  62.,  66.,  54.,  82.,  53.,  55.,  68.,  75.,
        76.,  46.,  63.,  61.,  55.,  88.,  62.,  40.,  75.,  86.,  48.,
        48.,  44.,  50.,  61.,  73.,  82.,  65.,  54.,  69.,  54.,  76.,
        47.,  78.,  46.,  74.,  93.,  68.,  85.,  84.,  67.,  41.,  62.,
        57.,  78.,  75.,  82.,  53.,  78.,  48.,  57.,  71.,  62.,  73.,
        60.,  52.,  90.,  68.,  87.,  65.,  81.,  92.,  55.,  40.,  83.,
        44.,  94.,  76.,  76.,  65.,  74.,  64.,  56.,  87.,  35.,  52.,
        74.,  55.,  63.,  72.,  72.,  77.,  93.,  44.,  65.,  72.,  64.,
        43.,  69.,  56.,  80.,  67.,  64.,  60.,  52.,  72.,  44.,  61.,
        80.,  51.,  50.,  57.,  49.,  75.,  92.,  5

In [36]:
y_test

array([ 68.,  81.,  51.,  63.,  94.,  76.,  45.,  61.,  48.,  55.,  98.,
        55.,  80.,  72.,  81.,  83.,  81.,  34.,  55.,  51.,  75.,  91.,
        61.,  56.,  72.,  55.,  50.,  38.,  82.,  57.,  74.,  87.,  81.,
        74.,  86.,  45.,  58.,  82.,  71.,  53.,  74.,  76.,  57.,  52.,
        62.,  75.,  68.,  65.,  67.,  57.,  82.,  57.,  51.,  66.,  76.,
        73.,  43.,  64.,  61.,  53.,  92.,  63.,  43.,  71.,  92.,  44.,
        52.,  40.,  50.,  61.,  70.,  80.,  64.,  59.,  70.,  59.,  79.,
        49.,  84.,  45.,  72.,  96.,  69.,  83.,  87.,  68.,  44.,  59.,
        57.,  76.,  75.,  82.,  53.,  71.,  50.,  58.,  77.,  62.,  81.,
        57.,  48.,  87.,  73.,  88.,  64.,  78.,  93.,  56.,  37.,  87.,
        43.,  96.,  81.,  80.,  68.,  75.,  60.,  55.,  86.,  35.,  56.,
        73.,  54.,  61.,  73.,  71.,  78.,  87.,  42.,  63.,  71.,  64.,
        44.,  73.,  55.,  82.,  65.,  70.,  61.,  62.,  74.,  46.,  59.,
        84.,  52.,  54.,  58.,  52.,  72.,  89.,  6

In [33]:
predictions

array([ 67.14478362,  78.85406526,  58.29823643,  62.38403668,
        89.17839396,  80.44859181,  44.10728258,  63.0534606 ,
        45.50808616,  55.56643496, 101.48033093,  58.92228133,
        79.06294369,  75.92589941,  81.28416787,  87.27490597,
        75.24169062,  37.24224471,  51.91250076,  48.75762219,
        77.03178528,  81.26141228,  63.28793839,  51.75133457,
        72.15146367,  55.24045058,  48.9299784 ,  42.7960364 ,
        80.70532916,  55.04739732,  71.18594355,  90.13400487,
        81.36404725,  76.94240369,  83.95259201,  42.04276067,
        62.48163706,  80.99969032,  63.89268407,  58.23469606,
        72.06498241,  74.34021368,  63.48130969,  54.51958401,
        65.1706052 ,  76.0877936 ,  64.93994248,  62.12782865,
        66.04679546,  53.78144407,  81.83983954,  53.04775764,
        54.76256895,  67.82310116,  74.59856575,  76.40338961,
        46.44833181,  62.92249866,  60.89892957,  55.49175466,
        88.37686035,  61.78368631,  40.44015797,  74.62